spring.application.name=lsmsdb-project

# --- MONGODB (Replica Set) ---
# Usiamo i nomi mappati! Così se il capo cambia, il driver lo trova.
spring.data.mongodb.uri=mongodb://mongo_primary:27017,mongo_secondary1:27018,mongo_secondary2:27019/ProgettoLSMSDB?replicaSet=rs0
spring.data.mongodb.auto-index-creation=true

# --- REDIS ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- NEO4J ---
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=passwordProgetto2026