spring.application.name=lsmsdb-project

# --- MONGODB (Replica Set Configuration) ---
# Fondamentale per il requisito "3 Replica Sets"
spring.data.mongodb.uri=mongodb://localhost:27017/lsmsdb
spring.data.mongodb.auto-index-creation=true

# --- REDIS (Master) ---
spring.data.redis.host=redis_master
spring.data.redis.port=6379

# --- NEO4J ---
# Bolt protocol per performance
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=passwordProgetto2026

# --- LOGGING ---
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.springframework.data.neo4j=INFO